package minecraft

import (
	"github.com/LilyPad/GoLilyPad/packet"
)

const (
	STRING_VERSION = string("1.8-pre3")
	MAGIC = string("§")

	PACKET_SERVER_HANDSHAKE = 0x00

	PACKET_CLIENT_KEEPALIVE = 0x00
	PACKET_CLIENT_JOIN_GAME = 0x01
	PACKET_CLIENT_CHAT = 0x02
	PACKET_CLIENT_TIME_UPDATE = 0x03
	PACKET_CLIENT_ENTITY_EQUIPMENT = 0x04
	PACKET_CLIENT_SPAWN_POSITION = 0x05
	PACKET_CLIENT_UPDATE_HEALTH = 0x06
	PACKET_CLIENT_RESPAWN = 0x07
	PACKET_CLIENT_PLAYER_POSITION_AND_LOOK = 0x08
	PACKET_CLIENT_HELD_ITEM_CHANGE = 0x09
	PACKET_CLIENT_USE_BED = 0x0A
	PACKET_CLIENT_ANIMATION = 0x0B
	PACKET_CLIENT_SPAWN_PLAYER = 0x0C
	PACKET_CLIENT_COLLECT_ITEM = 0x0D
	PACKET_CLIENT_SPAWN_OBJECT = 0x0E
	PACKET_CLIENT_SPAWN_MOB = 0x0F
	PACKET_CLIENT_SPAWN_PAINTING = 0x10
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB = 0x11
	PACKET_CLIENT_ENTITY_VELOCITY = 0x12
	PACKET_CLIENT_DESTROY_ENTITIES = 0x13
	PACKET_CLIENT_ENTITY = 0x14
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE = 0x15
	PACKET_CLIENT_ENTITY_LOOK = 0x16
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE = 0x17
	PACKET_CLIENT_ENTITY_TELEPORT = 0x18
	PACKET_CLIENT_ENTITY_HEAD_LOOK = 0x19
	PACKET_CLIENT_ENTITY_STATUS = 0x1A
	PACKET_CLIENT_ATTACH_ENTITY = 0x1B
	PACKET_CLIENT_ENTITY_METADATA = 0x1C
	PACKET_CLIENT_ENTITY_EFFECT = 0x1D
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT = 0x1E
	PACKET_CLIENT_SET_EXPERIENCE = 0x1F
	PACKET_CLIENT_ENTITY_PROPERTIES = 0x20
	PACKET_CLIENT_CHUNK_DATA = 0x21
	PACKET_CLIENT_MULTI_BLOCK_CHANGE = 0x22
	PACKET_CLIENT_BLOCK_CHANGE = 0x23
	PACKET_CLIENT_BLOCK_ACTION = 0x24
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION = 0x25
	PACKET_CLIENT_MAP_CHUNK_BULK = 0x26
	PACKET_CLIENT_EXPLOSION = 0x27
	PACKET_CLIENT_EFFECT = 0x28
	PACKET_CLIENT_SOUND_EFFECT = 0x29
	PACKET_CLIENT_PARTICLE = 0x2A
	PACKET_CLIENT_CHANGE_GAME_STATE = 0x2B
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY = 0x2C
	PACKET_CLIENT_OPEN_WINDOW = 0x2D
	PACKET_CLIENT_CLOSE_WINDOW = 0x2E
	PACKET_CLIENT_SET_SLOT = 0x2F
	PACKET_CLIENT_WINDOW_ITEMS = 0x30
	PACKET_CLIENT_WINDOW_PROPERTY = 0x31
	PACKET_CLIENT_CONFIRM_TRANSACTION = 0x32
	PACKET_CLIENT_UPDATE_SIGN = 0x33
	PACKET_CLIENT_MAPS = 0x34
	PACKET_CLIENT_UPDATE_BLOCK_ENTITY = 0x35
	PACKET_CLIENT_SIGN_EDITOR_OPEN = 0x36
	PACKET_CLIENT_STATISTICS = 0x37
	PACKET_CLIENT_PLAYER_LIST = 0x38
	PACKET_CLIENT_PLAYER_ABILITIES = 0x39
	PACKET_CLIENT_TAB_COMPLETE = 0x3A
	PACKET_CLIENT_SCOREBOARD_OBJECTIVE = 0x3B
	PACKET_CLIENT_UPDATE_SCORE = 0x3C
	PACKET_CLIENT_DISPLAY_SCOREBOARD = 0x3D
	PACKET_CLIENT_TEAMS = 0x3E
	PACKET_CLIENT_PLUGIN_MESSAGE = 0x3F
	PACKET_CLIENT_DISCONNECT = 0x40
	PACKET_CLIENT_DIFFICULTY = 0x41
	PACKET_CLIENT_COMBAT_EVENT = 0x42
	PACKET_CLIENT_CAMERA = 0x43
	PACKET_CLIENT_WORLD_BORDER = 0x44
	PACKET_CLIENT_TITLE = 0x45
	PACKET_CLIENT_SET_COMPRESSION = 0x46
	PACKET_CLIENT_PLAYER_LIST_HEAD_FOOT = 0x47
	PACKET_CLIENT_RESOURCE_PACK = 0x48
	PACKET_CLIENT_UPDATE_ENTITY_NBT = 0x49
	PACKET_SERVER_KEEPALIVE = 0x00
	PACKET_SERVER_CHAT = 0x01
	PACKET_SERVER_USE_ENTITY = 0x02
	PACKET_SERVER_PLAYER = 0x03
	PACKET_SERVER_PLAYER_POSITION = 0x04
	PACKET_SERVER_PLAYER_LOOK = 0x05
	PACKET_SERVER_PLAYER_LOOK_AND_POSITION = 0x06
	PACKET_SERVER_PLAYER_DIGGING = 0x07
	PACKET_SERVER_PLAYER_BLOCK_PLACEMENT = 0x08
	PACKET_SERVER_HELD_ITEM_CHANGE = 0x09
	PACKET_SERVER_ANIMATION = 0x0A
	PACKET_SERVER_ENTITY_ACTION = 0x0B
	PACKET_SERVER_STEER_VEHICLE = 0x0C
	PACKET_SERVER_CLOSE_WINDOW = 0x0D
	PACKET_SERVER_CLICK_WINDOW = 0x0E
	PACKET_SERVER_CONFIRM_TRANSACTION = 0x0F
	PACKET_SERVER_CREATIVE_INVENTORY_ACTION = 0x10
	PACKET_SERVER_ENCHANT_ITEM = 0x11
	PACKET_SERVER_UPDATE_SIGN = 0x12
	PACKET_SERVER_PLAYER_ABILITIES = 0x13
	PACKET_SERVER_TAB_COMPLETE = 0x14
	PACKET_SERVER_CLIENT_SETTINGS = 0x15
	PACKET_SERVER_CLIENT_STATUS = 0x16
	PACKET_SERVER_PLUGIN_MESSAGE = 0x17
	PACKET_SERVER_SPECTATE = 0x18
	PACKET_SERVER_RESOURCE_PACK_STATUS = 0x19

	PACKET_CLIENT_STATUS_RESPONSE = 0x00
	PACKET_CLIENT_STATUS_PING = 0x01
	PACKET_SERVER_STATUS_REQUEST = 0x00
	PACKET_SERVER_STATUS_PING = 0x01

	PACKET_CLIENT_LOGIN_DISCONNECT = 0x00
	PACKET_CLIENT_LOGIN_ENCRYPT_REQUEST = 0x01
	PACKET_CLIENT_LOGIN_SUCCESS = 0x02
	PACKET_CLIENT_LOGIN_SET_COMPRESSION = 0x03
	PACKET_SERVER_LOGIN_START = 0x00
	PACKET_SERVER_LOGIN_ENCRYPT_RESPONSE = 0x01
)

var Versions = []int { 46 }

var HandshakePacketServerCodec = packet.NewPacketCodecRegistryDual([]packet.PacketCodec {

}, []packet.PacketCodec {
	PACKET_SERVER_HANDSHAKE: new(packetServerHandshakeCodec),
})
var HandshakePacketClientCodec = HandshakePacketServerCodec.Flip()

var PlayPacketServerCodec = packet.NewPacketCodecRegistryDual([]packet.PacketCodec {
	PACKET_CLIENT_KEEPALIVE: NewPacketGenericCodec(PACKET_CLIENT_KEEPALIVE),
	PACKET_CLIENT_JOIN_GAME: new(packetClientJoinGameCodec),
	PACKET_CLIENT_CHAT: NewPacketGenericCodec(PACKET_CLIENT_CHAT),
	PACKET_CLIENT_TIME_UPDATE: NewPacketGenericCodec(PACKET_CLIENT_TIME_UPDATE),
	PACKET_CLIENT_ENTITY_EQUIPMENT: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_EQUIPMENT),
	PACKET_CLIENT_SPAWN_POSITION: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_POSITION),
	PACKET_CLIENT_UPDATE_HEALTH: NewPacketGenericCodec(PACKET_CLIENT_UPDATE_HEALTH),
	PACKET_CLIENT_RESPAWN: new(packetClientRespawnCodec),
	PACKET_CLIENT_PLAYER_POSITION_AND_LOOK: NewPacketGenericCodec(PACKET_CLIENT_PLAYER_POSITION_AND_LOOK),
	PACKET_CLIENT_HELD_ITEM_CHANGE: NewPacketGenericCodec(PACKET_CLIENT_HELD_ITEM_CHANGE),
	PACKET_CLIENT_USE_BED: NewPacketGenericCodec(PACKET_CLIENT_USE_BED),
	PACKET_CLIENT_ANIMATION: NewPacketGenericCodec(PACKET_CLIENT_ANIMATION),
	PACKET_CLIENT_SPAWN_PLAYER: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_PLAYER),
	PACKET_CLIENT_COLLECT_ITEM: NewPacketGenericCodec(PACKET_CLIENT_COLLECT_ITEM),
	PACKET_CLIENT_SPAWN_OBJECT: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_OBJECT),
	PACKET_CLIENT_SPAWN_MOB: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_MOB),
	PACKET_CLIENT_SPAWN_PAINTING: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_PAINTING),
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_EXPERIENCE_ORB),
	PACKET_CLIENT_ENTITY_VELOCITY: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_VELOCITY),
	PACKET_CLIENT_DESTROY_ENTITIES: NewPacketGenericCodec(PACKET_CLIENT_DESTROY_ENTITIES),
	PACKET_CLIENT_ENTITY: NewPacketGenericCodec(PACKET_CLIENT_ENTITY),
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_RELATIVE_MOVE),
	PACKET_CLIENT_ENTITY_LOOK: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_LOOK),
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE),
	PACKET_CLIENT_ENTITY_TELEPORT: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_TELEPORT),
	PACKET_CLIENT_ENTITY_HEAD_LOOK: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_HEAD_LOOK),
	PACKET_CLIENT_ENTITY_STATUS: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_STATUS),
	PACKET_CLIENT_ATTACH_ENTITY: NewPacketGenericCodec(PACKET_CLIENT_ATTACH_ENTITY),
	PACKET_CLIENT_ENTITY_METADATA: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_METADATA),
	PACKET_CLIENT_ENTITY_EFFECT: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_EFFECT),
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT: NewPacketGenericCodec(PACKET_CLIENT_REMOVE_ENTITY_EFFECT),
	PACKET_CLIENT_SET_EXPERIENCE: NewPacketGenericCodec(PACKET_CLIENT_SET_EXPERIENCE),
	PACKET_CLIENT_ENTITY_PROPERTIES: NewPacketGenericCodec(PACKET_CLIENT_ENTITY_PROPERTIES),
	PACKET_CLIENT_CHUNK_DATA: NewPacketGenericCodec(PACKET_CLIENT_CHUNK_DATA),
	PACKET_CLIENT_MULTI_BLOCK_CHANGE: NewPacketGenericCodec(PACKET_CLIENT_MULTI_BLOCK_CHANGE),
	PACKET_CLIENT_BLOCK_CHANGE: NewPacketGenericCodec(PACKET_CLIENT_BLOCK_CHANGE),
	PACKET_CLIENT_BLOCK_ACTION: NewPacketGenericCodec(PACKET_CLIENT_BLOCK_ACTION),
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION: NewPacketGenericCodec(PACKET_CLIENT_BLOCK_BREAK_ANIMATION),
	PACKET_CLIENT_MAP_CHUNK_BULK: NewPacketGenericCodec(PACKET_CLIENT_MAP_CHUNK_BULK),
	PACKET_CLIENT_EXPLOSION: NewPacketGenericCodec(PACKET_CLIENT_EXPLOSION),
	PACKET_CLIENT_EFFECT: NewPacketGenericCodec(PACKET_CLIENT_EFFECT),
	PACKET_CLIENT_SOUND_EFFECT: NewPacketGenericCodec(PACKET_CLIENT_SOUND_EFFECT),
	PACKET_CLIENT_PARTICLE: NewPacketGenericCodec(PACKET_CLIENT_PARTICLE),
	PACKET_CLIENT_CHANGE_GAME_STATE: NewPacketGenericCodec(PACKET_CLIENT_CHANGE_GAME_STATE),
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY: NewPacketGenericCodec(PACKET_CLIENT_SPAWN_GLOBAL_ENTITY),
	PACKET_CLIENT_OPEN_WINDOW: NewPacketGenericCodec(PACKET_CLIENT_OPEN_WINDOW),
	PACKET_CLIENT_CLOSE_WINDOW: NewPacketGenericCodec(PACKET_CLIENT_CLOSE_WINDOW),
	PACKET_CLIENT_SET_SLOT: NewPacketGenericCodec(PACKET_CLIENT_SET_SLOT),
	PACKET_CLIENT_WINDOW_ITEMS: NewPacketGenericCodec(PACKET_CLIENT_WINDOW_ITEMS),
	PACKET_CLIENT_WINDOW_PROPERTY: NewPacketGenericCodec(PACKET_CLIENT_WINDOW_PROPERTY),
	PACKET_CLIENT_CONFIRM_TRANSACTION: NewPacketGenericCodec(PACKET_CLIENT_CONFIRM_TRANSACTION),
	PACKET_CLIENT_UPDATE_SIGN: NewPacketGenericCodec(PACKET_CLIENT_UPDATE_SIGN),
	PACKET_CLIENT_MAPS: NewPacketGenericCodec(PACKET_CLIENT_MAPS),
	PACKET_CLIENT_UPDATE_BLOCK_ENTITY: NewPacketGenericCodec(PACKET_CLIENT_UPDATE_BLOCK_ENTITY),
	PACKET_CLIENT_SIGN_EDITOR_OPEN: NewPacketGenericCodec(PACKET_CLIENT_SIGN_EDITOR_OPEN),
	PACKET_CLIENT_STATISTICS: NewPacketGenericCodec(PACKET_CLIENT_STATISTICS),
	PACKET_CLIENT_PLAYER_LIST: new(packetClientPlayerListCodec),
	PACKET_CLIENT_PLAYER_ABILITIES: NewPacketGenericCodec(PACKET_CLIENT_PLAYER_ABILITIES),
	PACKET_CLIENT_TAB_COMPLETE: NewPacketGenericCodec(PACKET_CLIENT_TAB_COMPLETE),
	PACKET_CLIENT_SCOREBOARD_OBJECTIVE: new(packetClientScoreboardObjectiveCodec),
	PACKET_CLIENT_UPDATE_SCORE: NewPacketGenericCodec(PACKET_CLIENT_UPDATE_SCORE),
	PACKET_CLIENT_DISPLAY_SCOREBOARD: NewPacketGenericCodec(PACKET_CLIENT_DISPLAY_SCOREBOARD),
	PACKET_CLIENT_TEAMS: new(packetClientTeamsCodec),
	PACKET_CLIENT_PLUGIN_MESSAGE: NewPacketGenericCodec(PACKET_CLIENT_PLUGIN_MESSAGE),
	PACKET_CLIENT_DISCONNECT: new(packetClientDisconnectCodec),
	PACKET_CLIENT_DIFFICULTY: NewPacketGenericCodec(PACKET_CLIENT_DIFFICULTY),
	PACKET_CLIENT_COMBAT_EVENT: NewPacketGenericCodec(PACKET_CLIENT_COMBAT_EVENT),
	PACKET_CLIENT_CAMERA: NewPacketGenericCodec(PACKET_CLIENT_CAMERA),
	PACKET_CLIENT_WORLD_BORDER: NewPacketGenericCodec(PACKET_CLIENT_WORLD_BORDER),
	PACKET_CLIENT_TITLE: NewPacketGenericCodec(PACKET_CLIENT_TITLE),
	PACKET_CLIENT_SET_COMPRESSION: new(packetClientSetCompressionCodec),
	PACKET_CLIENT_PLAYER_LIST_HEAD_FOOT: NewPacketGenericCodec(PACKET_CLIENT_PLAYER_LIST_HEAD_FOOT),
	PACKET_CLIENT_RESOURCE_PACK: NewPacketGenericCodec(PACKET_CLIENT_RESOURCE_PACK),
	PACKET_CLIENT_UPDATE_ENTITY_NBT: NewPacketGenericCodec(PACKET_CLIENT_UPDATE_ENTITY_NBT),
}, []packet.PacketCodec {
	PACKET_SERVER_KEEPALIVE: NewPacketGenericCodec(PACKET_SERVER_KEEPALIVE),
	PACKET_SERVER_CHAT: NewPacketGenericCodec(PACKET_SERVER_CHAT),
	PACKET_SERVER_USE_ENTITY: NewPacketGenericCodec(PACKET_SERVER_USE_ENTITY),
	PACKET_SERVER_PLAYER: NewPacketGenericCodec(PACKET_SERVER_PLAYER),
	PACKET_SERVER_PLAYER_POSITION: NewPacketGenericCodec(PACKET_SERVER_PLAYER_POSITION),
	PACKET_SERVER_PLAYER_LOOK: NewPacketGenericCodec(PACKET_SERVER_PLAYER_LOOK),
	PACKET_SERVER_PLAYER_LOOK_AND_POSITION: NewPacketGenericCodec(PACKET_SERVER_PLAYER_LOOK_AND_POSITION),
	PACKET_SERVER_PLAYER_DIGGING: NewPacketGenericCodec(PACKET_SERVER_PLAYER_DIGGING),
	PACKET_SERVER_PLAYER_BLOCK_PLACEMENT: NewPacketGenericCodec(PACKET_SERVER_PLAYER_BLOCK_PLACEMENT),
	PACKET_SERVER_HELD_ITEM_CHANGE: NewPacketGenericCodec(PACKET_SERVER_HELD_ITEM_CHANGE),
	PACKET_SERVER_ANIMATION: NewPacketGenericCodec(PACKET_SERVER_ANIMATION),
	PACKET_SERVER_ENTITY_ACTION: NewPacketGenericCodec(PACKET_SERVER_ENTITY_ACTION),
	PACKET_SERVER_STEER_VEHICLE: NewPacketGenericCodec(PACKET_SERVER_STEER_VEHICLE),
	PACKET_SERVER_CLOSE_WINDOW: NewPacketGenericCodec(PACKET_SERVER_CLOSE_WINDOW),
	PACKET_SERVER_CLICK_WINDOW: NewPacketGenericCodec(PACKET_SERVER_CLICK_WINDOW),
	PACKET_SERVER_CONFIRM_TRANSACTION: NewPacketGenericCodec(PACKET_SERVER_CONFIRM_TRANSACTION),
	PACKET_SERVER_CREATIVE_INVENTORY_ACTION: NewPacketGenericCodec(PACKET_SERVER_CREATIVE_INVENTORY_ACTION),
	PACKET_SERVER_ENCHANT_ITEM: NewPacketGenericCodec(PACKET_SERVER_ENCHANT_ITEM),
	PACKET_SERVER_UPDATE_SIGN: NewPacketGenericCodec(PACKET_SERVER_UPDATE_SIGN),
	PACKET_SERVER_PLAYER_ABILITIES: NewPacketGenericCodec(PACKET_SERVER_PLAYER_ABILITIES),
	PACKET_SERVER_TAB_COMPLETE: NewPacketGenericCodec(PACKET_SERVER_TAB_COMPLETE),
	PACKET_SERVER_CLIENT_SETTINGS: new(packetServerClientSettingsCodec),
	PACKET_SERVER_CLIENT_STATUS: NewPacketGenericCodec(PACKET_SERVER_CLIENT_STATUS),
	PACKET_SERVER_PLUGIN_MESSAGE: new(packetServerPluginMessageCodec),
	PACKET_SERVER_SPECTATE: NewPacketGenericCodec(PACKET_SERVER_SPECTATE),
	PACKET_SERVER_RESOURCE_PACK_STATUS: NewPacketGenericCodec(PACKET_SERVER_RESOURCE_PACK_STATUS),
})
var PlayPacketClientCodec = PlayPacketServerCodec.Flip()

var StatusPacketServerCodec = packet.NewPacketCodecRegistryDual([]packet.PacketCodec {
	PACKET_CLIENT_STATUS_RESPONSE: new(packetClientStatusResponseCodec),
	PACKET_CLIENT_STATUS_PING: new(packetClientStatusPingCodec),
}, []packet.PacketCodec {
	PACKET_SERVER_STATUS_REQUEST: new(packetServerStatusRequestCodec),
	PACKET_SERVER_STATUS_PING: new(packetServerStatusPingCodec),
})
var StatusPacketClientCodec = StatusPacketServerCodec.Flip()

var LoginPacketServerCodec = packet.NewPacketCodecRegistryDual([]packet.PacketCodec {
	PACKET_CLIENT_LOGIN_DISCONNECT: new(packetClientLoginDisconnectCodec),
	PACKET_CLIENT_LOGIN_ENCRYPT_REQUEST: new(packetClientLoginEncryptRequestCodec),
	PACKET_CLIENT_LOGIN_SUCCESS: new(packetClientLoginSuccessCodec),
	PACKET_CLIENT_LOGIN_SET_COMPRESSION: new(packetClientLoginSetCompressionCodec),
}, []packet.PacketCodec {
	PACKET_SERVER_LOGIN_START: new(packetServerLoginStartCodec),
	PACKET_SERVER_LOGIN_ENCRYPT_RESPONSE: new(packetServerLoginEncryptResponseCodec),
})
var LoginPacketClientCodec = LoginPacketServerCodec.Flip()

var PlayPacketClientEntityIntPositions = [][]int {
	PACKET_CLIENT_ENTITY_STATUS: { 0 },
	PACKET_CLIENT_ATTACH_ENTITY: { 0, 4 },
}
var PlayPacketClientEntityVarIntPositions = []bool {
	PACKET_CLIENT_ENTITY_EQUIPMENT: true,
	PACKET_CLIENT_USE_BED: true,
	PACKET_CLIENT_COLLECT_ITEM: true, // TODO change the second argument too?
	PACKET_CLIENT_ANIMATION: true,
	PACKET_CLIENT_SPAWN_PLAYER: true,
	PACKET_CLIENT_SPAWN_OBJECT: true,
	PACKET_CLIENT_SPAWN_MOB: true,
	PACKET_CLIENT_SPAWN_PAINTING: true,
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB: true,
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY: true,
	PACKET_CLIENT_ENTITY_VELOCITY: true,
	PACKET_CLIENT_ENTITY: true,
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE: true,
	PACKET_CLIENT_ENTITY_LOOK: true,
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE: true,
	PACKET_CLIENT_ENTITY_TELEPORT: true,
	PACKET_CLIENT_ENTITY_HEAD_LOOK: true,
	PACKET_CLIENT_ENTITY_METADATA: true,
	PACKET_CLIENT_ENTITY_EFFECT: true,
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT: true,
	PACKET_CLIENT_ENTITY_PROPERTIES: true,
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION: true,
	// TODO combat event
	PACKET_CLIENT_UPDATE_ENTITY_NBT: true,
}
var PlayPacketServerEntityIntPositions = [][]int {

}
var PlayPacketServerEntityVarIntPositions = []bool {
	PACKET_SERVER_USE_ENTITY: true,
	PACKET_SERVER_ENTITY_ACTION: true,
}

var Play17PacketClientEntityIntPositions = [][]int {
	PACKET_CLIENT_ENTITY_EQUIPMENT: { 0 },
	PACKET_CLIENT_USE_BED: { 0 },
	PACKET_CLIENT_COLLECT_ITEM: { 0, 4 },
	PACKET_CLIENT_ENTITY_VELOCITY: { 0 },
	PACKET_CLIENT_ENTITY: { 0 },
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE: { 0 },
	PACKET_CLIENT_ENTITY_LOOK: { 0 },
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE: { 0 },
	PACKET_CLIENT_ENTITY_TELEPORT: { 0 },
	PACKET_CLIENT_ENTITY_HEAD_LOOK: { 0 },
	PACKET_CLIENT_ENTITY_STATUS: { 0 },
	PACKET_CLIENT_ATTACH_ENTITY: { 0, 4 },
	PACKET_CLIENT_ENTITY_METADATA: { 0 },
	PACKET_CLIENT_ENTITY_EFFECT: { 0 },
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT: { 0 },
	PACKET_CLIENT_ENTITY_PROPERTIES: { 0 },
}
var Play17PacketClientEntityVarIntPositions = []bool {
	PACKET_CLIENT_ANIMATION: true,
	PACKET_CLIENT_SPAWN_PLAYER: true,
	PACKET_CLIENT_SPAWN_OBJECT: true,
	PACKET_CLIENT_SPAWN_MOB: true,
	PACKET_CLIENT_SPAWN_PAINTING: true,
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB: true,
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION: true,
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY: true,
}
var Play17PacketServerEntityIntPositions = [][]int {
	PACKET_SERVER_USE_ENTITY: { 0 },
	PACKET_SERVER_ANIMATION: { 0 },
	PACKET_SERVER_ENTITY_ACTION: { 0 },
}
var Play17PacketServerEntityVarIntPositions = []bool {

}
