package minecraft

import "github.com/LilyPad/GoLilyPad/packet"

const (
	VERSION = 5
	STRING_VERSION = string("1.7.6")
	MAGIC = string("§")

	PACKET_SERVER_HANDSHAKE = 0x00

	PACKET_CLIENT_KEEPALIVE = 0x00
	PACKET_CLIENT_JOIN_GAME = 0x01
	PACKET_CLIENT_CHAT = 0x02
	PACKET_CLIENT_TIME_UPDATE = 0x03
	PACKET_CLIENT_ENTITY_EQUIPMENT = 0x04
	PACKET_CLIENT_SPAWN_POSITION = 0x05
	PACKET_CLIENT_UPDATE_HEALTH = 0x06
	PACKET_CLIENT_RESPAWN = 0x07
	PACKET_CLIENT_PLAYER_POSITION_AND_LOOK = 0x08
	PACKET_CLIENT_HELD_ITEM_CHANGE = 0x09
	PACKET_CLIENT_USE_BED = 0x0A
	PACKET_CLIENT_ANIMATION = 0x0B
	PACKET_CLIENT_SPAWN_PLAYER = 0x0C
	PACKET_CLIENT_COLLECT_ITEM = 0x0D
	PACKET_CLIENT_SPAWN_OBJECT = 0x0E
	PACKET_CLIENT_SPAWN_MOB = 0x0F
	PACKET_CLIENT_SPAWN_PAINTING = 0x10
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB = 0x11
	PACKET_CLIENT_ENTITY_VELOCITY = 0x12
	PACKET_CLIENT_DESTROY_ENTITIES = 0x13
	PACKET_CLIENT_ENTITY = 0x14
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE = 0x15
	PACKET_CLIENT_ENTITY_LOOK = 0x16
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE = 0x17
	PACKET_CLIENT_ENTITY_TELEPORT = 0x18
	PACKET_CLIENT_ENTITY_HEAD_LOOK = 0x19
	PACKET_CLIENT_ENTITY_STATUS = 0x1A
	PACKET_CLIENT_ATTACH_ENTITY = 0x1B
	PACKET_CLIENT_ENTITY_METADATA = 0x1C
	PACKET_CLIENT_ENTITY_EFFECT = 0x1D
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT = 0x1E
	PACKET_CLIENT_SET_EXPERIENCE = 0x1F
	PACKET_CLIENT_ENTITY_PROPERTIES = 0x20
	PACKET_CLIENT_CHUNK_DATA = 0x21
	PACKET_CLIENT_MULTI_BLOCK_CHANGE = 0x22
	PACKET_CLIENT_BLOCK_CHANGE = 0x23
	PACKET_CLIENT_BLOCK_ACTION = 0x24
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION = 0x25
	PACKET_CLIENT_MAP_CHUNK_BULK = 0x26
	PACKET_CLIENT_EXPLOSION = 0x27
	PACKET_CLIENT_EFFECT = 0x28
	PACKET_CLIENT_SOUND_EFFECT = 0x29
	PACKET_CLIENT_PARTICLE = 0x2A
	PACKET_CLIENT_CHANGE_GAME_STATE = 0x2B
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY = 0x2C
	PACKET_CLIENT_OPEN_WINDOW = 0x2D
	PACKET_CLIENT_CLOSE_WINDOW = 0x2E
	PACKET_CLIENT_SET_SLOT = 0x2F
	PACKET_CLIENT_WINDOW_ITEMS = 0x30
	PACKET_CLIENT_WINDOW_PROPERTY = 0x31
	PACKET_CLIENT_CONFIRM_TRANSACTION = 0x32
	PACKET_CLIENT_UPDATE_SIGN = 0x33
	PACKET_CLIENT_MAPS = 0x34
	PACKET_CLIENT_UPDATE_BLOCK_ENTITY = 0x35
	PACKET_CLIENT_SIGN_EDITOR_OPEN = 0x36
	PACKET_CLIENT_STATISTICS = 0x37
	PACKET_CLIENT_PLAYER_LIST_ITEM = 0x38
	PACKET_CLIENT_PLAYER_ABILITIES = 0x39
	PACKET_CLIENT_TAB_COMPLETE = 0x3A
	PACKET_CLIENT_SCOREBOARD_OBJECTIVE = 0x3B
	PACKET_CLIENT_UPDATE_SCORE = 0x3C
	PACKET_CLIENT_DISPLAY_SCOREBOARD = 0x3D
	PACKET_CLIENT_TEAMS = 0x3E
	PACKET_CLIENT_PLUGIN_MESSAGE = 0x3F
	PACKET_CLIENT_DISCONNECT = 0x40
	PACKET_SERVER_KEEPALIVE = 0x00
	PACKET_SERVER_CHAT = 0x01
	PACKET_SERVER_USE_ENTITY = 0x02
	PACKET_SERVER_PLAYER = 0x03
	PACKET_SERVER_PLAYER_POSITION = 0x04
	PACKET_SERVER_PLAYER_LOOK = 0x05
	PACKET_SERVER_PLAYER_LOOK_AND_POSITION = 0x06
	PACKET_SERVER_PLAYER_DIGGING = 0x07
	PACKET_SERVER_PLAYER_BLOCK_PLACEMENT = 0x08
	PACKET_SERVER_HELD_ITEM_CHANGE = 0x09
	PACKET_SERVER_ANIMATION = 0x0A
	PACKET_SERVER_ENTITY_ACTION = 0x0B
	PACKET_SERVER_STEER_VEHICLE = 0x0C
	PACKET_SERVER_CLOSE_WINDOW = 0x0D
	PACKET_SERVER_CLICK_WINDOW = 0x0E
	PACKET_SERVER_CONFIRM_TRANSACTION = 0x0F
	PACKET_SERVER_CREATIVE_INVENTORY_ACTION = 0x10
	PACKET_SERVER_ENCHANT_ITEM = 0x11
	PACKET_SERVER_UPDATE_SIGN = 0x12
	PACKET_SERVER_PLAYER_ABILITIES = 0x13
	PACKET_SERVER_TAB_COMPLETE = 0x14
	PACKET_SERVER_CLIENT_SETTINGS = 0x15
	PACKET_SERVER_CLIENT_STATUS = 0x16
	PACKET_SERVER_PLUGIN_MESSAGE = 0x17

	PACKET_CLIENT_STATUS_RESPONSE = 0x00
	PACKET_CLIENT_STATUS_PING = 0x01
	PACKET_SERVER_STATUS_REQUEST = 0x00
	PACKET_SERVER_STATUS_PING = 0x01

	PACKET_CLIENT_LOGIN_DISCONNECT = 0x00
	PACKET_CLIENT_LOGIN_ENCRYPT_REQUEST = 0x01
	PACKET_CLIENT_LOGIN_SUCCESS = 0x02
	PACKET_SERVER_LOGIN_START = 0x00
	PACKET_SERVER_LOGIN_ENCRYPT_RESPONSE = 0x01
)

var HandshakePacketClientCodecs = []packet.PacketCodec {

}
var HandshakePacketClientCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(HandshakePacketClientCodecs))

var HandshakePacketServerCodecs = []packet.PacketCodec {
	PACKET_SERVER_HANDSHAKE: &PacketServerHandshakeCodec{},
}
var HandshakePacketServerCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(HandshakePacketServerCodecs))

var PlayPacketClientCodecs = []packet.PacketCodec {
	PACKET_CLIENT_KEEPALIVE: &PacketGenericCodec{PACKET_CLIENT_KEEPALIVE},
	PACKET_CLIENT_JOIN_GAME: &PacketClientJoinGameCodec{},
	PACKET_CLIENT_CHAT: &PacketGenericCodec{PACKET_CLIENT_CHAT},
	PACKET_CLIENT_TIME_UPDATE: &PacketGenericCodec{PACKET_CLIENT_TIME_UPDATE},
	PACKET_CLIENT_ENTITY_EQUIPMENT: &PacketGenericCodec{PACKET_CLIENT_ENTITY_EQUIPMENT},
	PACKET_CLIENT_SPAWN_POSITION: &PacketGenericCodec{PACKET_CLIENT_SPAWN_POSITION},
	PACKET_CLIENT_UPDATE_HEALTH: &PacketGenericCodec{PACKET_CLIENT_UPDATE_HEALTH},
	PACKET_CLIENT_RESPAWN: &PacketClientRespawnCodec{},
	PACKET_CLIENT_PLAYER_POSITION_AND_LOOK: &PacketGenericCodec{PACKET_CLIENT_PLAYER_POSITION_AND_LOOK},
	PACKET_CLIENT_HELD_ITEM_CHANGE: &PacketGenericCodec{PACKET_CLIENT_HELD_ITEM_CHANGE},
	PACKET_CLIENT_USE_BED: &PacketGenericCodec{PACKET_CLIENT_USE_BED},
	PACKET_CLIENT_ANIMATION: &PacketGenericCodec{PACKET_CLIENT_ANIMATION},
	PACKET_CLIENT_SPAWN_PLAYER: &PacketGenericCodec{PACKET_CLIENT_SPAWN_PLAYER},
	PACKET_CLIENT_COLLECT_ITEM: &PacketGenericCodec{PACKET_CLIENT_COLLECT_ITEM},
	PACKET_CLIENT_SPAWN_OBJECT: &PacketGenericCodec{PACKET_CLIENT_SPAWN_OBJECT},
	PACKET_CLIENT_SPAWN_MOB: &PacketGenericCodec{PACKET_CLIENT_SPAWN_MOB},
	PACKET_CLIENT_SPAWN_PAINTING: &PacketGenericCodec{PACKET_CLIENT_SPAWN_PAINTING},
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB: &PacketGenericCodec{PACKET_CLIENT_SPAWN_EXPERIENCE_ORB},
	PACKET_CLIENT_ENTITY_VELOCITY: &PacketGenericCodec{PACKET_CLIENT_ENTITY_VELOCITY},
	PACKET_CLIENT_DESTROY_ENTITIES: &PacketGenericCodec{PACKET_CLIENT_DESTROY_ENTITIES},
	PACKET_CLIENT_ENTITY: &PacketGenericCodec{PACKET_CLIENT_ENTITY},
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE: &PacketGenericCodec{PACKET_CLIENT_ENTITY_RELATIVE_MOVE},
	PACKET_CLIENT_ENTITY_LOOK: &PacketGenericCodec{PACKET_CLIENT_ENTITY_LOOK},
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE: &PacketGenericCodec{PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE},
	PACKET_CLIENT_ENTITY_TELEPORT: &PacketGenericCodec{PACKET_CLIENT_ENTITY_TELEPORT},
	PACKET_CLIENT_ENTITY_HEAD_LOOK: &PacketGenericCodec{PACKET_CLIENT_ENTITY_HEAD_LOOK},
	PACKET_CLIENT_ENTITY_STATUS: &PacketGenericCodec{PACKET_CLIENT_ENTITY_STATUS},
	PACKET_CLIENT_ATTACH_ENTITY: &PacketGenericCodec{PACKET_CLIENT_ATTACH_ENTITY},
	PACKET_CLIENT_ENTITY_METADATA: &PacketGenericCodec{PACKET_CLIENT_ENTITY_METADATA},
	PACKET_CLIENT_ENTITY_EFFECT: &PacketGenericCodec{PACKET_CLIENT_ENTITY_EFFECT},
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT: &PacketGenericCodec{PACKET_CLIENT_REMOVE_ENTITY_EFFECT},
	PACKET_CLIENT_SET_EXPERIENCE: &PacketGenericCodec{PACKET_CLIENT_SET_EXPERIENCE},
	PACKET_CLIENT_ENTITY_PROPERTIES: &PacketGenericCodec{PACKET_CLIENT_ENTITY_PROPERTIES},
	PACKET_CLIENT_CHUNK_DATA: &PacketGenericCodec{PACKET_CLIENT_CHUNK_DATA},
	PACKET_CLIENT_MULTI_BLOCK_CHANGE: &PacketGenericCodec{PACKET_CLIENT_MULTI_BLOCK_CHANGE},
	PACKET_CLIENT_BLOCK_CHANGE: &PacketGenericCodec{PACKET_CLIENT_BLOCK_CHANGE},
	PACKET_CLIENT_BLOCK_ACTION: &PacketGenericCodec{PACKET_CLIENT_BLOCK_ACTION},
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION: &PacketGenericCodec{PACKET_CLIENT_BLOCK_BREAK_ANIMATION},
	PACKET_CLIENT_MAP_CHUNK_BULK: &PacketGenericCodec{PACKET_CLIENT_MAP_CHUNK_BULK},
	PACKET_CLIENT_EXPLOSION: &PacketGenericCodec{PACKET_CLIENT_EXPLOSION},
	PACKET_CLIENT_EFFECT: &PacketGenericCodec{PACKET_CLIENT_EFFECT},
	PACKET_CLIENT_SOUND_EFFECT: &PacketGenericCodec{PACKET_CLIENT_SOUND_EFFECT},
	PACKET_CLIENT_PARTICLE: &PacketGenericCodec{PACKET_CLIENT_PARTICLE},
	PACKET_CLIENT_CHANGE_GAME_STATE: &PacketGenericCodec{PACKET_CLIENT_CHANGE_GAME_STATE},
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY: &PacketGenericCodec{PACKET_CLIENT_SPAWN_GLOBAL_ENTITY},
	PACKET_CLIENT_OPEN_WINDOW: &PacketGenericCodec{PACKET_CLIENT_OPEN_WINDOW},
	PACKET_CLIENT_CLOSE_WINDOW: &PacketGenericCodec{PACKET_CLIENT_CLOSE_WINDOW},
	PACKET_CLIENT_SET_SLOT: &PacketGenericCodec{PACKET_CLIENT_SET_SLOT},
	PACKET_CLIENT_WINDOW_ITEMS: &PacketGenericCodec{PACKET_CLIENT_WINDOW_ITEMS},
	PACKET_CLIENT_WINDOW_PROPERTY: &PacketGenericCodec{PACKET_CLIENT_WINDOW_PROPERTY},
	PACKET_CLIENT_CONFIRM_TRANSACTION: &PacketGenericCodec{PACKET_CLIENT_CONFIRM_TRANSACTION},
	PACKET_CLIENT_UPDATE_SIGN: &PacketGenericCodec{PACKET_CLIENT_UPDATE_SIGN},
	PACKET_CLIENT_MAPS: &PacketGenericCodec{PACKET_CLIENT_MAPS},
	PACKET_CLIENT_UPDATE_BLOCK_ENTITY: &PacketGenericCodec{PACKET_CLIENT_UPDATE_BLOCK_ENTITY},
	PACKET_CLIENT_SIGN_EDITOR_OPEN: &PacketGenericCodec{PACKET_CLIENT_SIGN_EDITOR_OPEN},
	PACKET_CLIENT_STATISTICS: &PacketGenericCodec{PACKET_CLIENT_STATISTICS},
	PACKET_CLIENT_PLAYER_LIST_ITEM: &PacketClientPlayerListItemCodec{},
	PACKET_CLIENT_PLAYER_ABILITIES: &PacketGenericCodec{PACKET_CLIENT_PLAYER_ABILITIES},
	PACKET_CLIENT_TAB_COMPLETE: &PacketGenericCodec{PACKET_CLIENT_TAB_COMPLETE},
	PACKET_CLIENT_SCOREBOARD_OBJECTIVE: &PacketClientScoreboardObjectiveCodec{},
	PACKET_CLIENT_UPDATE_SCORE: &PacketGenericCodec{PACKET_CLIENT_UPDATE_SCORE},
	PACKET_CLIENT_DISPLAY_SCOREBOARD: &PacketGenericCodec{PACKET_CLIENT_DISPLAY_SCOREBOARD},
	PACKET_CLIENT_TEAMS: &PacketClientTeamsCodec{},
	PACKET_CLIENT_PLUGIN_MESSAGE: &PacketGenericCodec{PACKET_CLIENT_PLUGIN_MESSAGE},
	PACKET_CLIENT_DISCONNECT: &PacketClientDisconnectCodec{},
}
var PlayPacketClientEntityIntPositions = [][]int {
	PACKET_CLIENT_ENTITY_EQUIPMENT: { 0 },
	PACKET_CLIENT_USE_BED: { 0 },
	PACKET_CLIENT_COLLECT_ITEM: { 0, 4 },
	PACKET_CLIENT_ENTITY_VELOCITY: { 0 },
	PACKET_CLIENT_ENTITY: { 0 },
	PACKET_CLIENT_ENTITY_RELATIVE_MOVE: { 0 },
	PACKET_CLIENT_ENTITY_LOOK: { 0 },
	PACKET_CLIENT_ENTITY_LOOK_AND_RELATIVE_MOVE: { 0 },
	PACKET_CLIENT_ENTITY_TELEPORT: { 0 },
	PACKET_CLIENT_ENTITY_HEAD_LOOK: { 0 },
	PACKET_CLIENT_ENTITY_STATUS: { 0 },
	PACKET_CLIENT_ATTACH_ENTITY: { 0, 4 },
	PACKET_CLIENT_ENTITY_METADATA: { 0 },
	PACKET_CLIENT_ENTITY_EFFECT: { 0 },
	PACKET_CLIENT_REMOVE_ENTITY_EFFECT: { 0 },
	PACKET_CLIENT_ENTITY_PROPERTIES: { 0 },
}
var PlayPacketClientEntityVarIntPositions = []bool {
	PACKET_CLIENT_ANIMATION: true,
	PACKET_CLIENT_SPAWN_PLAYER: true,
	PACKET_CLIENT_SPAWN_OBJECT: true,
	PACKET_CLIENT_SPAWN_MOB: true,
	PACKET_CLIENT_SPAWN_PAINTING: true,
	PACKET_CLIENT_SPAWN_EXPERIENCE_ORB: true,
	PACKET_CLIENT_BLOCK_BREAK_ANIMATION: true,
	PACKET_CLIENT_SPAWN_GLOBAL_ENTITY: true,
}
var PlayPacketClientCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(PlayPacketClientCodecs))

var PlayPacketServerCodecs = []packet.PacketCodec {
	PACKET_SERVER_KEEPALIVE: &PacketGenericCodec{PACKET_SERVER_KEEPALIVE},
	PACKET_SERVER_CHAT: &PacketGenericCodec{PACKET_SERVER_CHAT},
	PACKET_SERVER_USE_ENTITY: &PacketGenericCodec{PACKET_SERVER_USE_ENTITY},
	PACKET_SERVER_PLAYER: &PacketGenericCodec{PACKET_SERVER_PLAYER},
	PACKET_SERVER_PLAYER_POSITION: &PacketGenericCodec{PACKET_SERVER_PLAYER_POSITION},
	PACKET_SERVER_PLAYER_LOOK: &PacketGenericCodec{PACKET_SERVER_PLAYER_LOOK},
	PACKET_SERVER_PLAYER_LOOK_AND_POSITION: &PacketGenericCodec{PACKET_SERVER_PLAYER_LOOK_AND_POSITION},
	PACKET_SERVER_PLAYER_DIGGING: &PacketGenericCodec{PACKET_SERVER_PLAYER_DIGGING},
	PACKET_SERVER_PLAYER_BLOCK_PLACEMENT: &PacketGenericCodec{PACKET_SERVER_PLAYER_BLOCK_PLACEMENT},
	PACKET_SERVER_HELD_ITEM_CHANGE: &PacketGenericCodec{PACKET_SERVER_HELD_ITEM_CHANGE},
	PACKET_SERVER_ANIMATION: &PacketGenericCodec{PACKET_SERVER_ANIMATION},
	PACKET_SERVER_ENTITY_ACTION: &PacketGenericCodec{PACKET_SERVER_ENTITY_ACTION},
	PACKET_SERVER_STEER_VEHICLE: &PacketGenericCodec{PACKET_SERVER_STEER_VEHICLE},
	PACKET_SERVER_CLOSE_WINDOW: &PacketGenericCodec{PACKET_SERVER_CLOSE_WINDOW},
	PACKET_SERVER_CLICK_WINDOW: &PacketGenericCodec{PACKET_SERVER_CLICK_WINDOW},
	PACKET_SERVER_CONFIRM_TRANSACTION: &PacketGenericCodec{PACKET_SERVER_CONFIRM_TRANSACTION},
	PACKET_SERVER_CREATIVE_INVENTORY_ACTION: &PacketGenericCodec{PACKET_SERVER_CREATIVE_INVENTORY_ACTION},
	PACKET_SERVER_ENCHANT_ITEM: &PacketGenericCodec{PACKET_SERVER_ENCHANT_ITEM},
	PACKET_SERVER_UPDATE_SIGN: &PacketGenericCodec{PACKET_SERVER_UPDATE_SIGN},
	PACKET_SERVER_PLAYER_ABILITIES: &PacketGenericCodec{PACKET_SERVER_PLAYER_ABILITIES},
	PACKET_SERVER_TAB_COMPLETE: &PacketGenericCodec{PACKET_SERVER_TAB_COMPLETE},
	PACKET_SERVER_CLIENT_SETTINGS: &PacketServerClientSettingsCodec{},
	PACKET_SERVER_CLIENT_STATUS: &PacketGenericCodec{PACKET_SERVER_CLIENT_STATUS},
	PACKET_SERVER_PLUGIN_MESSAGE: &PacketGenericCodec{PACKET_SERVER_PLUGIN_MESSAGE},
}
var PlayPacketServerEntityIntPositions = [][]int {
	PACKET_SERVER_USE_ENTITY: { 0 },
	PACKET_SERVER_ANIMATION: { 0 },
	PACKET_SERVER_ENTITY_ACTION: { 0 },
}
var PlayPacketServerEntityVarIntPositions = []bool {

}
var PlayPacketServerCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(PlayPacketServerCodecs))

var StatusPacketClientCodecs = []packet.PacketCodec {
	PACKET_CLIENT_STATUS_RESPONSE: &PacketClientStatusResponseCodec{},
	PACKET_CLIENT_STATUS_PING: &PacketClientStatusPingCodec{},
}
var StatusPacketClientCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(StatusPacketClientCodecs))

var StatusPacketServerCodecs = []packet.PacketCodec {
	PACKET_SERVER_STATUS_REQUEST: &PacketServerStatusRequestCodec{},
	PACKET_SERVER_STATUS_PING: &PacketServerStatusPingCodec{},
}
var StatusPacketServerCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(StatusPacketServerCodecs))

var LoginPacketClientCodecs = []packet.PacketCodec {
	PACKET_CLIENT_LOGIN_DISCONNECT: &PacketClientLoginDisconnectCodec{},
	PACKET_CLIENT_LOGIN_ENCRYPT_REQUEST: &PacketClientLoginEncryptRequestCodec{},
	PACKET_CLIENT_LOGIN_SUCCESS: &PacketClientLoginSuccessCodec{},
}

var LoginPacketClientCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(LoginPacketClientCodecs))

var LoginPacketServerCodecs = []packet.PacketCodec {
	PACKET_SERVER_LOGIN_START: &PacketServerLoginStartCodec{},
	PACKET_SERVER_LOGIN_ENCRYPT_RESPONSE: &PacketServerLoginEncryptResponseCodec{},
}
var LoginPacketServerCodec = packet.NewPacketCodecVarIntLength(packet.NewPacketCodecRegistry(LoginPacketServerCodecs))
